openapi: 3.0.3
info:
  title: E-commerce Product Prediction API
  description: |
    Intelligent E-commerce API with vector search, sales analytics, and prediction capabilities.
    This API provides advanced features for product management, search, analytics, and sales predictions.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080
    description: Development Server
  - url: https://api.example.com
    description: Production Server

tags:
  - name: Products
    description: Product management operations
  - name: Orders
    description: Order management operations
  - name: Vector Search
    description: AI-powered vector similarity search
  - name: Analytics
    description: Sales analytics and reporting
  - name: Predictions
    description: AI-powered sales predictions
  - name: MCP
    description: Model-Centric Protocol for LLM integration

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api-key

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "P123456"
          description: Unique product identifier
        name:
          type: string
          example: "Wireless Bluetooth Headphones"
          description: Product name
        category:
          type: string
          example: "Electronics"
          description: Product category
        brand:
          type: string
          example: "AudioTech"
          description: Product brand
        price:
          type: number
          format: double
          example: 99.99
          description: Product price
        createTimestamp:
          type: string
          format: date-time
          example: "2023-05-15T10:30:00"
          description: Product creation timestamp
        description:
          type: string
          example: "High-quality wireless headphones with noise cancellation"
          description: Detailed product description

    Order:
      type: object
      properties:
        orderId:
          type: string
          example: "ORD98765"
          description: Unique order identifier
        productId:
          type: string
          example: "P123456"
          description: Product identifier
        buyerId:
          type: string
          example: "USER4321"
          description: Customer who made the purchase
        sellerId:
          type: string
          example: "SELLER789"
          description: Seller who sold the product
        unitPrice:
          type: number
          format: double
          example: 99.99
          description: Price per unit
        quantity:
          type: integer
          example: 2
          description: Number of units ordered
        totalPrice:
          type: number
          format: double
          example: 199.98
          description: Total order price
        timestamp:
          type: string
          format: date-time
          example: "2023-07-20T14:25:00"
          description: Order timestamp

    SalesSearchRequest:
      type: object
      properties:
        topN:
          type: integer
          example: 10
          description: Number of top products to retrieve
        startTime:
          type: string
          example: "2023/01"
          description: Start time in year/month format
        endTime:
          type: string
          example: "2023/12"
          description: End time in year/month format
        sellerId:
          type: string
          example: "SELLER789"
          description: Seller ID to filter by
        category:
          type: string
          example: "Electronics"
          description: Category to filter by
      required:
        - topN
        - startTime
        - sellerId

    SalesPredictionRequest:
      type: object
      properties:
        productId:
          type: string
          example: "P123456"
          description: Product ID to predict sales for
        sellerId:
          type: string
          example: "SELLER789"
          description: Seller ID
        startTime:
          type: string
          example: "2023/01"
          description: Start time in year/month format
        endTime:
          type: string
          example: "2023/12"
          description: End time in year/month format
      required:
        - productId
        - sellerId
        - startTime

paths:
  /v1/products:
    get:
      tags:
        - Products
      summary: Get all products
      description: Retrieve all products, optionally filtered by category and/or seller ID
      operationId: getAllProducts
      parameters:
        - name: category
          in: query
          description: Filter by product category
          required: false
          schema:
            type: string
          example: "Electronics"
        - name: sellerId
          in: query
          description: Filter by seller ID
          required: false
          schema:
            type: string
          example: "SELLER789"
      responses:
        '200':
          description: Successfully retrieved products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  count:
                    type: integer
                    example: 25
                  category:
                    type: string
                    example: "Electronics"
                  sellerId:
                    type: string
                    example: "SELLER789"

  /v1/product/{id}:
    get:
      tags:
        - Products
      summary: Get product by ID
      description: Retrieve a product by its unique identifier
      operationId: getProductById
      parameters:
        - name: id
          in: path
          description: Product ID
          required: true
          schema:
            type: string
          example: "P123456"
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                type: object
                properties:
                  product:
                    $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

  /v1/products/search/similar:
    post:
      tags:
        - Products
        - Vector Search
      summary: Search similar products
      description: Find products similar to the given description using vector similarity search
      operationId: searchSimilarProducts
      requestBody:
        description: Search parameters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: "wireless noise-cancelling headphones"
                  description: Text description to search for similar products
                productId:
                  type: string
                  example: "P123456"
                  description: Optional product ID to find similar products
                limit:
                  type: integer
                  example: 5
              required:
                - description
      responses:
        '200':
          description: Successfully retrieved similar products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  count:
                    type: integer
                    example: 5

  /v1/orders:
    get:
      tags:
        - Orders
      summary: Get recent orders
      description: Retrieve recent orders with pagination support (max 100 items per page)
      operationId: getRecentOrders
      parameters:
        - name: page
          in: query
          description: Page number (0-based)
          required: false
          schema:
            type: integer
            default: 0
          example: 0
        - name: size
          in: query
          description: Page size (max 100)
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
          example: 20
      responses:
        '200':
          description: Successfully retrieved orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  currentPage:
                    type: integer
                    example: 0
                  totalItems:
                    type: integer
                    example: 250
                  totalPages:
                    type: integer
                    example: 13

  /v1/sales/search:
    post:
      tags:
        - Analytics
      summary: Search for top selling products
      description: Find top selling products by time range, category, and seller ID
      operationId: searchTopSellingProducts
      requestBody:
        description: Search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalesSearchRequest'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        productId:
                          type: string
                          example: "P123456"
                        totalQuantity:
                          type: integer
                          example: 250
                        name:
                          type: string
                          example: "Wireless Bluetooth Headphones"
                        category:
                          type: string
                          example: "Electronics"
                        brand:
                          type: string
                          example: "AudioTech"
                        price:
                          type: number
                          format: double
                          example: 99.99
                  count:
                    type: integer
                    example: 10
                  query:
                    $ref: '#/components/schemas/SalesSearchRequest'
        '400':
          description: Bad request due to invalid parameters

  /v1/sales/predict:
    post:
      tags:
        - Predictions
      summary: Predict product sales
      description: Predict future sales for a specific product
      operationId: predictProductSales
      requestBody:
        description: Prediction parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalesPredictionRequest'
      responses:
        '200':
          description: Sales prediction
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: object
                    additionalProperties:
                      type: object
                    example:
                      "2023/06": 
                        quantity: 45
                        revenue: 4495.5
                      "2023/07": 
                        quantity: 52
                        revenue: 5199.48
                  product:
                    $ref: '#/components/schemas/Product'
                  query:
                    $ref: '#/components/schemas/SalesPredictionRequest'
        '400':
          description: Bad request due to invalid parameters
        '404':
          description: Product not found

  /api/mcp/products:
    get:
      tags:
        - MCP
      summary: Get all products (MCP)
      description: Retrieve all products with optional filtering, formatted for LLM consumption
      operationId: mcpGetAllProducts
      parameters:
        - name: category
          in: query
          description: Filter by product category
          required: false
          schema:
            type: string
          example: "Electronics"
        - name: sellerId
          in: query
          description: Filter by seller ID
          required: false
          schema:
            type: string
          example: "SELLER789"
      responses:
        '200':
          description: Successfully retrieved products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

  /api/mcp/products/search/similar:
    post:
      tags:
        - MCP
        - Vector Search
      summary: Find similar products by text
      description: Uses vector embeddings to find semantically similar products based on provided text
      operationId: mcpSearchSimilarProducts
      requestBody:
        description: Search request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "premium wireless headphones"
                limit:
                  type: integer
                  example: 5
              required:
                - text
      responses:
        '200':
          description: Successfully retrieved similar products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

  /api/mcp/products/top:
    get:
      tags:
        - MCP
        - Analytics
      summary: Get top selling products
      description: Retrieve the top selling products for a seller in the last 30 days
      operationId: mcpGetTopSellingProducts
      parameters:
        - name: sellerId
          in: query
          description: Seller ID to filter by
          required: false
          schema:
            type: string
          example: "SELLER789"
        - name: limit
          in: query
          description: Number of top products to retrieve
          required: false
          schema:
            type: integer
            default: 5
          example: 10
      responses:
        '200':
          description: Successfully retrieved top products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object

  /api/mcp/orders/customer/{customerId}:
    get:
      tags:
        - MCP
        - Orders
      summary: Get customer orders
      description: Retrieve all orders for a specific customer
      operationId: mcpGetCustomerOrders
      parameters:
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: string
          example: "USER4321"
      responses:
        '200':
          description: Successfully retrieved customer orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'

  /api/mcp/predictions/sales:
    get:
      tags:
        - MCP
        - Predictions
      summary: Predict future sales
      description: Generate sales predictions for the specified number of days
      operationId: mcpPredictSales
      parameters:
        - name: days
          in: query
          description: Number of days to predict
          required: false
          schema:
            type: integer
            default: 7
          example: 30
      responses:
        '200':
          description: Successfully generated sales predictions
          content:
            application/json:
              schema:
                type: object
                properties:
                  predictions:
                    type: object
                    additionalProperties:
                      type: number
                    example:
                      "P123456": 2499.70
                      "P234567": 599.85
                      "P345678": 1299.95
                  days:
                    type: integer
                    example: 30 